baseURL = 'http://me.sierra-lang.net/'
languageCode = 'en-us'
title = 'Personal Website and Blog'
theme = "hello-friend-ng"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts"
[[menu.main]]
  identifier = "books"
  name = "Books"
  url = "/books"
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects"
